import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
// import ClientSideProviderTest from "@/components/clientSideProviderTest/page";

import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Next.js HomePage",
    template: "%s | Next.js 14 learning"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          {/* <ClientSideProviderTest> */}
            <Navbar />
            {children}
            <Footer />
          {/* </ClientSideProviderTest> */}
        </div>
      </body>
    </html>
  );
}
